name = "hotnow-youtube-proxy"
type = "javascript"
main = "cloudflare-worker.ts"
compatibility_date = "2024-11-01"
account_id = "1b3be71944be5604a67db1c2f4e85051"

# 环境变量
[env.production]
name = "hotnow-youtube-proxy"
vars = { INVIDIOUS_INSTANCE = "https://iv.ggtyler.dev" }

[build]
command = ""
cwd = "."
