name = "hotnow-youtube-proxy"
type = "javascript"
main = "cloudflare-worker.ts"
compatibility_date = "2024-11-01"
account_id = "818bc3779fc21ad273be0dccb094ea3d"

# 环境变量
[env.production]
name = "hotnow-youtube-proxy"
vars = { INVIDIOUS_INSTANCE = "https://iv.ggtyler.dev" }

[build]
command = ""
cwd = "."
